name: Enforce Target Branch
 
on:
  pull_request:
    types:
      - opened
      - synchronize
 
jobs:
  enforce-target-branch:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check Target Branch
        run: |
          # Extract target branch from the pull request
          target_branch=$(echo ${{ github.event.pull_request.base.ref }} | sed 's/refs\/heads\///')
          echo $github.base_ref
          echo $github.head_ref

          # # Specify the allowed target branches
          # allowed_branches=("main" "develop")
 
          # # Check if the target branch is allowed
          # if [[ " ${allowed_branches[@]} " =~ " ${target_branch} " ]]; then
          #   echo "Target branch is allowed."
          # else
          #   echo "Error: Invalid target branch. PRs can only be merged from ${allowed_branches[@]}."
          #   exit 1
          # fi
