name: Enforce Target Branch
 
on:
  pull_request:
    types:
      - opened
      - synchronize
 
jobs:
  enforce-target-branch:
    runs-on: ubuntu-latest
 
    steps:
      - name: Check Target Branch
        run: |
          echo "Merging from: ${{ github.base_ref }}"
          echo "Target branch: ${{ github.head_ref }}"
          # Specify the allowed base branches
          allowed_branches=("jira-main")
          # Check if the base branch is allowed
          if [[ " ${allowed_branches[@]} " =~ " ${{ github.base_ref }} " ]]; then
            echo "Base branch is allowed."
          else
            echo "Error: Invalid base branch. PRs can only be merged from ${allowed_branches[@]}."
            exit 1
          fi
