name: Update CODEOWNERS
on:
  pull_request:
    types:
      - closed
jobs:
  update-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Git
        run: |
            git config --global user.email "github-actions@dummy.com"
            git config --global user.name "GitHub Actions"
        env:
          GITHUB_TOKE: ${{ secrets.GHA_PAT }}
      - name: Update CODEOWNERS
        run: |
          connector_main="jira-main"
          internal_rel="jira-rel-1.0"
          google_rel="jira-rel-1.0-google"
          git fetch origin ${{ github.base_ref }}
          git checkout ${{ github.base_ref }}
          if [[ ${{ github.base_ref }} == $connector_main ]]; then
              echo "* @ruihuang_psl @zjun_psl @gunagya_psl @abhishekkmr_psl @yogendra-rajput_psl @ravi-vishwakarma1_psl @swapnilag_psl @swapnil-paranjpe_psl @venkata-bathalapalli_psl" > CODEOWNERS
              git commit -am "GitHub Actions Worflow updated CODEOWNERS" & true
          elif [[ ${{ github.base_ref }} == $internal_rel ]]; then
              echo "* @ruihuang_psl @zjun_psl @gunagya_psl @abhishekkmr_psl @yogendra-rajput_psl @ravi-vishwakarma1_psl @swapnilag_psl @swapnil-paranjpe_psl @venkata-bathalapalli_psl" > CODEOWNERS
              git commit -am "GitHub Actions Worflow updated CODEOWNERS" & true
          elif [[ ${{ github.base_ref }} == $google_rel ]]; then
              echo "* @ruihuang_psl @zjun_psl @gunagya_psl @abhishekkmr_psl @yogendra-rajput_psl @ravi-vishwakarma1_psl @swapnilag_psl @swapnil-paranjpe_psl @venkata-bathalapalli_psl" > CODEOWNERS
              git commit -am "GitHub Actions Worflow updated CODEOWNERS" & true
          else
              echo "No action required, exiting!""
              exit 0
          fi
      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.GHA_PAT }}
          branch: ${{ github.base_ref }}
          unprotect_reviews: true
