name: Update CODEOWNERS
on:
  pull_request:
    types:
      - closed
jobs:
  update-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Git
        run: |
            git config --global user.email "github-actions@dummy.com"
            git config --global user.name "GitHub Actions"
        env:
          GITHUB_TOKE: ${{ secrets.GHA_PAT }}
      - name: Debug
        run: |
          echo "GitHub Token: $GITHUB_TOKEN"
          git config --global --get-regexp 'url.*.insteadof'
          git remote -v
      - name: Update CODEOWNERS
        run: |
          git fetch origin master
          git checkout master
          echo "* @ruihuang_psl @zjun_psl @gunagya_psl @abhishekkmr_psl @yogendra-rajput_psl @ravi-vishwakarma1_psl @swapnilag_psl @swapnil-paranjpe_psl @venkata-bathalapalli_psl" > CODEOWNERS
          git commit -am "GitHub Actions Worflow updated CODEOWNERS"
          git push
        env:
          GITHUB_TOKE: ${{ secrets.GHA_PAT }}
