name: Update CODEOWNERS
on:
  pull_request:
    types:
      - closed
jobs:
  update-codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Git
        run: |
            git config --global user.email "github-actions@dummy.com"
            git config --global user.name "GitHub Actions"
        env:
          GITHUB_TOKE: ${{ secrets.GHA_PAT }}
      - id: update_codeowners
        name: Update CODEOWNERS
        run: |
          connector_main="jira-main"
          internal_rel="jira-rel-1.0"
          google_rel="jira-rel-1.0-google"
          git fetch origin ${{ github.base_ref }}
          git checkout ${{ github.base_ref }}
          if [[ ${{ github.base_ref }} == $connector_main ]]; then
              echo "* @chetan-gangurde_psl @parikshit-pandhare_psl @omkar-bodhane_psl @sravanakumar-d_psl @dhiraj-chaudhari_psl @leena-herwadkar_psl @utkarsha-mahajan_psl @swapnil-patil9_psl @Sagar-Lonkar_psl @lakma-mahendar_psl @ankur-mathur_psl @pankaj-kaushal_psl @arun-murugan_psl @ajith-kannath_psl @rakesh-agarwal1_psl" > CODEOWNERS
              git commit -am "GitHub Actions Worflow updated CODEOWNERS" & true
          elif [[ ${{ github.base_ref }} == $internal_rel ]]; then
              echo "* @ankur-mathur_psl @pankaj-kaushal_psl @arun-murugan_psl @ajith-kannath_psl @rakesh-agarwal1_psl @swapnil-paranjpe_psl" > CODEOWNERS
              git commit -am "GitHub Actions Worflow updated CODEOWNERS" & true
          elif [[ ${{ github.base_ref }} == $google_rel ]]; then
              echo "* @ruihuang_psl @zjun_psl @gunagya_psl @abhishekkmr_psl @yogendra-rajput_psl @ravi-vishwakarma1_psl @swapnilag_psl @swapnil-paranjpe_psl @venkata-bathalapalli_psl" > CODEOWNERS
              git commit -am "GitHub Actions Worflow updated CODEOWNERS" & true
              git push -f
          else
              echo "No action required, exiting!"
              exit 1
          fi
      # - name: Push to protected branch
      #   uses: CasperWA/push-protected@v2
      #   if: steps.update_codeowners.conclusion == 'success'
      #   with:
      #     token: ${{ secrets.GHA_PAT }}
      #     branch: ${{ github.base_ref }}
      #     unprotect_reviews: true
