name: Passing values
on:
  workflow_dispatch:
jobs:
  job1:
    outputs:
      VALUE_FROM_JOB1: ${{ steps.step1.outputs.VALUE_FROM_STEP1 }}
    runs-on: ubuntu-latest
    steps:
      - name: pass value to another step
        id: step1
        run: echo "VALUE_FROM_STEP1=value1" >> $GITHUB_OUTPUT
      - name: Display value from step 1
        run: echo "Values from step1 $VALUE_FROM_STEP1"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
        - run: echo ${{ needs.job1.outputs.VALUE_FROM_STEP1 }}
