name: test-diff

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test-diff:

    runs-on: ubuntu-latest
    env:
      PROJECTS: "vais-salesforce-cloud-connector,vais-onedrive-cloud-connector"
    steps:
    - uses: actions/checkout@v3
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        COUNT=0
        echo "List of changed file: ${{ steps.files.outputs.all }}"
        STRING_LIST=(${PROJECTS//,/ })
        for value in "${STRING_LIST[@]}"; do
          echo "Value: $value"
          if grep -q "$value" "${{ steps.files.outputs.all }}"; then
            echo "Project $value changed"
          fi
        done
        

