name: test-diff

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test-diff:

    runs-on: ubuntu-latest
    env:
      PROJECTS: "vais-box-cloud-connector,vais-confluence-cloud-connector,vais-dropbox-cloud-connector,vais-internal-website-connector,vais-jira-cloud-connector,vais-onedrive-cloud-connector,vais-salesforce-cloud-connector,vais-servicenow-cloud-connector,vais-sharepoint-cloud-connector,vais-slack-cloud-connector"
    steps:
    - uses: actions/checkout@v3
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        COUNT=0
        echo "List of changed file: ${{ steps.files.outputs.all }}"
        STRING_LIST=(${PROJECTS//,/ })
        for value in "${STRING_LIST[@]}"; do
          if echo ${{ steps.files.outputs.all }} | grep -q -w "$value" ; then
              echo "Send request for $value"
          else
              echo "Do not send request for $value"
          fi
        done
        

